<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ini_set('memory_limit', '512M');
        DB::disableQueryLog();
        $districts = [
            ['id'=>36, 'district'=>'Anantnag', 'state_id'=>15],
            ['id'=>37, 'district'=>'Bandipore', 'state_id'=>15],
            ['id'=>38, 'district'=>'Baramulla', 'state_id'=>15],
            ['id'=>39, 'district'=>'Budgam', 'state_id'=>15],
            ['id'=>40, 'district'=>'Doda', 'state_id'=>15],
            ['id'=>41, 'district'=>'Ganderbal', 'state_id'=>15],
            ['id'=>42, 'district'=>'Jammu', 'state_id'=>15],
            ['id'=>43, 'district'=>'Kargil', 'state_id'=>15],
            ['id'=>44, 'district'=>'Kathua', 'state_id'=>15],
            ['id'=>45, 'district'=>'Kishtwar', 'state_id'=>15],
            ['id'=>46, 'district'=>'Kulgam', 'state_id'=>15],
            ['id'=>47, 'district'=>'Kupwara', 'state_id'=>15],
            ['id'=>48, 'district'=>'Leh (Ladakh)', 'state_id'=>15],
            ['id'=>49, 'district'=>'Poonch', 'state_id'=>15],
            ['id'=>50, 'district'=>'Pulwama', 'state_id'=>15],
            ['id'=>51, 'district'=>'Rajouri', 'state_id'=>15],
            ['id'=>52, 'district'=>'Ramban', 'state_id'=>15],
            ['id'=>53, 'district'=>'Reasi', 'state_id'=>15],
            ['id'=>54, 'district'=>'Samba', 'state_id'=>15],
            ['id'=>55, 'district'=>'Shopian', 'state_id'=>15],
            ['id'=>56, 'district'=>'Srinagar', 'state_id'=>15],
            ['id'=>57, 'district'=>'Udhampur', 'state_id'=>15],
            ['id'=>58, 'district'=>'Bilaspur (Himachal Pradesh)', 'state_id'=>14],
            ['id'=>59, 'district'=>'Chamba', 'state_id'=>14],
            ['id'=>60, 'district'=>'Hamirpur (Himachal Pradesh)', 'state_id'=>14],
            ['id'=>61, 'district'=>'Kangra', 'state_id'=>14],
            ['id'=>62, 'district'=>'Kinnaur', 'state_id'=>14],
            ['id'=>63, 'district'=>'Kullu', 'state_id'=>14],
            ['id'=>64, 'district'=>'Lahul & Spiti', 'state_id'=>14],
            ['id'=>65, 'district'=>'Mandi', 'state_id'=>14],
            ['id'=>66, 'district'=>'Shimla', 'state_id'=>14],
            ['id'=>67, 'district'=>'Sirmaur', 'state_id'=>14],
            ['id'=>68, 'district'=>'Solan', 'state_id'=>14],
            ['id'=>69, 'district'=>'Una', 'state_id'=>14],
            ['id'=>70, 'district'=>'Amritsar', 'state_id'=>28],
            ['id'=>71, 'district'=>'Barnala', 'state_id'=>28],
            ['id'=>72, 'district'=>'Bathinda', 'state_id'=>28],
            ['id'=>73, 'district'=>'Faridkot', 'state_id'=>28],
            ['id'=>74, 'district'=>'Fatehgarh Sahib', 'state_id'=>28],
            ['id'=>75, 'district'=>'Firozpur', 'state_id'=>28],
            ['id'=>76, 'district'=>'Gurdaspur', 'state_id'=>28],
            ['id'=>77, 'district'=>'Hoshiarpur', 'state_id'=>28],
            ['id'=>78, 'district'=>'Jalandhar', 'state_id'=>28],
            ['id'=>79, 'district'=>'Kapurthala', 'state_id'=>28],
            ['id'=>80, 'district'=>'Ludhiana', 'state_id'=>28],
            ['id'=>81, 'district'=>'Mansa', 'state_id'=>28],
            ['id'=>82, 'district'=>'Moga', 'state_id'=>28],
            ['id'=>83, 'district'=>'Muktsar', 'state_id'=>28],
            ['id'=>84, 'district'=>'Patiala', 'state_id'=>28],
            ['id'=>85, 'district'=>'Rupnagar (Ropar)', 'state_id'=>28],
            ['id'=>86, 'district'=>'Sahibzada Ajit Singh Nagar (Mohali)', 'state_id'=> 28],
            ['id'=>87, 'district'=>'Sangrur', 'state_id'=>28],
            ['id'=>88, 'district'=>'Shahid Bhagat Singh Nagar (Nawanshahr)','state_id'=> 28],
            ['id'=>89, 'district'=>'Tarn Taran', 'state_id'=>28],
            ['id'=>90, 'district'=>'Chandigarh','state_id'=> 6],
            ['id'=>91, 'district'=>'Almora', 'state_id'=>34],
            ['id'=>92, 'district'=>'Bageshwar', 'state_id'=>34],
            ['id'=>93, 'district'=>'Chamoli', 'state_id'=>34],
            ['id'=>94, 'district'=>'Champawat', 'state_id'=>34],
            ['id'=>95, 'district'=>'Dehradun', 'state_id'=>34],
            ['id'=>96, 'district'=>'Haridwar', 'state_id'=>34],
            ['id'=>97, 'district'=>'Nainital', 'state_id'=>34],
            ['id'=>98, 'district'=>'Pauri Garhwal', 'state_id'=>34],
            ['id'=>99, 'district'=>'Pithoragarh', 'state_id'=>34],
            ['id'=>100,'district'=> 'Rudraprayag', 'state_id'=>34],
            ['id'=>101,'district'=> 'Tehri Garhwal', 'state_id'=>34],
            ['id'=>102,'district'=> 'Udham Singh Nagar', 'state_id'=>34],
            ['id'=>103,'district'=> 'Uttarkashi', 'state_id'=>34],
            ['id'=>104,'district'=> 'Ambala', 'state_id'=>13],
            ['id'=>105,'district'=> 'Bhiwani', 'state_id'=>13],
            ['id'=>106,'district'=> 'Faridabad', 'state_id'=>13],
            ['id'=>107,'district'=> 'Fatehabad', 'state_id'=>13],
            ['id'=>108,'district'=> 'Gurgaon', 'state_id'=>13],
            ['id'=>109,'district'=> 'Hisar', 'state_id'=>13],
            ['id'=>110,'district'=> 'Jhajjar', 'state_id'=>13],
            ['id'=>111,'district'=> 'Jind', 'state_id'=>13],
            ['id'=>112,'district'=> 'Kaithal', 'state_id'=>13],
            ['id'=>113,'district'=> 'Karnal', 'state_id'=>13],
            ['id'=>114,'district'=> 'Kurukshetra', 'state_id'=>13],
            ['id'=>115,'district'=> 'Mahendragarh', 'state_id'=>13],
            ['id'=>116,'district'=> 'Mewat', 'state_id'=>13],
            ['id'=>117,'district'=> 'Palwal', 'state_id'=>13],
            ['id'=>118,'district'=> 'Panchkula', 'state_id'=>13],
            ['id'=>119,'district'=> 'Panipat', 'state_id'=>13],
            ['id'=>120,'district'=> 'Rewari', 'state_id'=>13],
            ['id'=>121,'district'=> 'Rohtak', 'state_id'=>13],
            ['id'=>122,'district'=> 'Sirsa', 'state_id'=>13],
            ['id'=>123,'district'=> 'Sonipat', 'state_id'=>13],
            ['id'=>124,'district'=> 'Yamuna Nagar', 'state_id'=>13],
            ['id'=>125,'district'=> 'Central Delhi', 'state_id'=>10],
            ['id'=>126,'district'=> 'East Delhi', 'state_id'=>10],
            ['id'=>127,'district'=> 'New Delhi', 'state_id'=>10],
            ['id'=>128,'district'=> 'North Delhi', 'state_id'=>10],
            ['id'=>129,'district'=> 'North East Delhi', 'state_id'=>10],
            ['id'=>130,'district'=> 'North West Delhi', 'state_id'=>10],
            ['id'=>131,'district'=> 'South Delhi', 'state_id'=>10],
            ['id'=>132,'district'=> 'South West Delhi', 'state_id'=>10],
            ['id'=>133,'district'=> 'West Delhi', 'state_id'=>10],
            ['id'=>134,'district'=> 'Ajmer', 'state_id'=>29],
            ['id'=>135,'district'=> 'Alwar', 'state_id'=>29],
            ['id'=>136,'district'=> 'Banswara', 'state_id'=>29],
            ['id'=>137,'district'=> 'Baran', 'state_id'=>29],
            ['id'=>138,'district'=> 'Barmer', 'state_id'=>29],
            ['id'=>139,'district'=> 'Bharatpur', 'state_id'=>29],
            ['id'=>140,'district'=> 'Bhilwara', 'state_id'=>29],
            ['id'=>141,'district'=> 'Bikaner', 'state_id'=>29],
            ['id'=>142,'district'=> 'Bundi', 'state_id'=>29],
            ['id'=>143,'district'=> 'Chittorgarh', 'state_id'=>29],
            ['id'=>144,'district'=> 'Churu', 'state_id'=>29],
            ['id'=>145,'district'=> 'Dausa', 'state_id'=>29],
            ['id'=>146,'district'=> 'Dholpur', 'state_id'=>29],
            ['id'=>147,'district'=> 'Dungarpur', 'state_id'=>29],
            ['id'=>148,'district'=> 'Ganganagar', 'state_id'=>29],
            ['id'=>149,'district'=> 'Hanumangarh', 'state_id'=>29],
            ['id'=>150,'district'=> 'Jaipur', 'state_id'=>29],
            ['id'=>151,'district'=> 'Jaisalmer', 'state_id'=>29],
            ['id'=>152,'district'=> 'Jalor', 'state_id'=>29],
            ['id'=>153,'district'=> 'Jhalawar', 'state_id'=>29],
            ['id'=>154,'district'=> 'Jhunjhunu', 'state_id'=>29],
            ['id'=>155,'district'=> 'Jodhpur', 'state_id'=>29],
            ['id'=>156,'district'=> 'Karauli', 'state_id'=>29],
            ['id'=>157,'district'=> 'Kota', 'state_id'=>29],
            ['id'=>158,'district'=> 'Nagaur', 'state_id'=>29],
            ['id'=>159,'district'=> 'Pali', 'state_id'=>29],
            ['id'=>160,'district'=> 'Pratapgarh (Rajasthan)', 'state_id'=>29],
            ['id'=>161,'district'=> 'Rajsamand', 'state_id'=>29],
            ['id'=>162,'district'=> 'Sawai Madhopur', 'state_id'=>29],
            ['id'=>163,'district'=> 'Sikar', 'state_id'=>29],
            ['id'=>164,'district'=> 'Sirohi', 'state_id'=>29],
            ['id'=>165,'district'=> 'Tonk', 'state_id'=>29],
            ['id'=>166,'district'=> 'Udaipur', 'state_id'=>29],
            ['id'=>167,'district'=> 'Agra', 'state_id'=>33],
            ['id'=>168,'district'=> 'Aligarh', 'state_id'=>33],
            ['id'=>169,'district'=> 'Allahabad', 'state_id'=>33],
            ['id'=>170,'district'=> 'Ambedkar Nagar', 'state_id'=>33],
            ['id'=>171,'district'=> 'Auraiya', 'state_id'=>33],
            ['id'=>172,'district'=> 'Azamgarh', 'state_id'=>33],
            ['id'=>173,'district'=> 'Bagpat', 'state_id'=>33],
            ['id'=>174,'district'=> 'Bahraich', 'state_id'=>33],
            ['id'=>175,'district'=> 'Ballia', 'state_id'=>33],
            ['id'=>176,'district'=> 'Balrampur', 'state_id'=>33],
            ['id'=>177,'district'=> 'Banda', 'state_id'=>33],
            ['id'=>178,'district'=> 'Barabanki', 'state_id'=>33],
            ['id'=>179,'district'=> 'Bareilly', 'state_id'=>33],
            ['id'=>180,'district'=> 'Basti', 'state_id'=>33],
            ['id'=>181,'district'=> 'Bijnor', 'state_id'=>33],
            ['id'=>182,'district'=> 'Budaun', 'state_id'=>33],
            ['id'=>183,'district'=> 'Bulandshahr', 'state_id'=>33],
            ['id'=>184,'district'=> 'Chandauli', 'state_id'=>33],
            ['id'=>185,'district'=> 'Chitrakoot', 'state_id'=>33],
            ['id'=>186,'district'=> 'Deoria', 'state_id'=>33],
            ['id'=>187,'district'=> 'Etah', 'state_id'=>33],
            ['id'=>188,'district'=> 'Etawah', 'state_id'=>33],
            ['id'=>189,'district'=> 'Faizabad', 'state_id'=>33],
            ['id'=>190,'district'=> 'Farrukhabad', 'state_id'=>33],
            ['id'=>191,'district'=> 'Fatehpur', 'state_id'=>33],
            ['id'=>192,'district'=> 'Firozabad', 'state_id'=>33],
            ['id'=>193,'district'=> 'Gautam Buddha Nagar', 'state_id'=>33],
            ['id'=>194,'district'=> 'Ghaziabad', 'state_id'=>33],
            ['id'=>195,'district'=> 'Ghazipur', 'state_id'=>33],
            ['id'=>196,'district'=> 'Gonda', 'state_id'=>33],
            ['id'=>197,'district'=> 'Gorakhpur', 'state_id'=>33],
            ['id'=>198,'district'=> 'Hamirpur', 'state_id'=>33],
            ['id'=>199,'district'=> 'Hardoi', 'state_id'=>33],
            ['id'=>200,'district'=> 'Hathras', 'state_id'=>33],
            ['id'=>201,'district'=> 'Jalaun', 'state_id'=>33],
            ['id'=>202,'district'=> 'Jaunpur', 'state_id'=>33],
            ['id'=>203,'district'=> 'Jhansi', 'state_id'=>33],
            ['id'=>204,'district'=> 'Jyotiba Phule Nagar', 'state_id'=>33],
            ['id'=>205,'district'=> 'Kannauj', 'state_id'=>33],
            ['id'=>206,'district'=> 'Kanpur Dehat', 'state_id'=>33],
            ['id'=>207,'district'=> 'Kanpur Nagar', 'state_id'=>33],
            ['id'=>208,'district'=> 'Kanshiram Nagar', 'state_id'=>33],
            ['id'=>209,'district'=> 'Kaushambi', 'state_id'=>33],
            ['id'=>210,'district'=> 'Kheri', 'state_id'=>33],
            ['id'=>211,'district'=> 'Kushinagar', 'state_id'=>33],
            ['id'=>212,'district'=> 'Lalitpur', 'state_id'=>33],
            ['id'=>213,'district'=> 'Lucknow', 'state_id'=>33],
            ['id'=>214,'district'=> 'Maharajganj', 'state_id'=>33],
            ['id'=>215,'district'=> 'Mahoba', 'state_id'=>33],
            ['id'=>216,'district'=> 'Mainpuri', 'state_id'=>33],
            ['id'=>217,'district'=> 'Mathura', 'state_id'=>33],
            ['id'=>218,'district'=> 'Mau', 'state_id'=>33],
            ['id'=>219,'district'=> 'Meerut', 'state_id'=>33],
            ['id'=>220,'district'=> 'Mirzapur', 'state_id'=>33],
            ['id'=>221,'district'=> 'Moradabad', 'state_id'=>33],
            ['id'=>222,'district'=> 'Muzaffarnagar', 'state_id'=>33],
            ['id'=>223,'district'=> 'Pilibhit', 'state_id'=>33],
            ['id'=>224,'district'=> 'Pratapgarh', 'state_id'=>33],
            ['id'=>225,'district'=> 'Rae Bareli', 'state_id'=>33],
            ['id'=>226,'district'=> 'Rampur', 'state_id'=>33],
            ['id'=>227,'district'=> 'Saharanpur', 'state_id'=>33],
            ['id'=>228,'district'=> 'Sant Kabir Nagar', 'state_id'=>33],
            ['id'=>229,'district'=> 'Sant Ravidas Nagar (Bhadohi)', 'state_id'=>33],
            ['id'=>230,'district'=> 'Shahjahanpur', 'state_id'=>33],
            ['id'=>231,'district'=> 'Shrawasti', 'state_id'=>33],
            ['id'=>232,'district'=> 'Siddharthnagar', 'state_id'=>33],
            ['id'=>233,'district'=> 'Sitapur', 'state_id'=>33],
            ['id'=>234,'district'=> 'Sonbhadra', 'state_id'=>33],
            ['id'=>235,'district'=> 'Sultanpur', 'state_id'=>33],
            ['id'=>236,'district'=> 'Unnao', 'state_id'=>33],
            ['id'=>237,'district'=> 'Varanasi', 'state_id'=>33],
            ['id'=>238,'district'=> 'Araria','state_id'=> 5],
            ['id'=>239,'district'=> 'Arwal','state_id'=> 5],
            ['id'=>240,'district'=> 'Aurangabad (Bihar)','state_id'=> 5],
            ['id'=>241,'district'=> 'Banka','state_id'=> 5],
            ['id'=>242,'district'=> 'Begusarai','state_id'=> 5],
            ['id'=>243,'district'=> 'Bhagalpur','state_id'=> 5],
            ['id'=>244,'district'=> 'Bhojpur','state_id'=> 5],
            ['id'=>245,'district'=> 'Buxar','state_id'=> 5],
            ['id'=>246,'district'=> 'Darbhanga','state_id'=> 5],
            ['id'=>247,'district'=> 'East Champaran','state_id'=> 5],
            ['id'=>248,'district'=> 'Gaya','state_id'=> 5],
            ['id'=>249,'district'=> 'Gopalganj','state_id'=> 5],
            ['id'=>250,'district'=> 'Jamui','state_id'=> 5],
            ['id'=>251,'district'=> 'Jehanabad','state_id'=> 5],
            ['id'=>252,'district'=> 'Kaimur (Bhabua)','state_id'=> 5],
            ['id'=>253,'district'=> 'Katihar','state_id'=> 5],
            ['id'=>254,'district'=> 'Khagaria','state_id'=> 5],
            ['id'=>255,'district'=> 'Kishanganj','state_id'=> 5],
            ['id'=>256,'district'=> 'Lakhisarai','state_id'=> 5],
            ['id'=>257,'district'=> 'Madhepura','state_id'=> 5],
            ['id'=>258,'district'=> 'Madhubani','state_id'=> 5],
            ['id'=>259,'district'=> 'Munger','state_id'=> 5],
            ['id'=>260,'district'=> 'Muzaffarpur','state_id'=> 5],
            ['id'=>261,'district'=> 'Nalanda','state_id'=> 5],
            ['id'=>262,'district'=> 'Nawada','state_id'=> 5],
            ['id'=>263,'district'=> 'Patna','state_id'=> 5],
            ['id'=>264,'district'=> 'Purnia','state_id'=> 5],
            ['id'=>265,'district'=> 'Rohtas','state_id'=> 5],
            ['id'=>266,'district'=> 'Saharsa','state_id'=> 5],
            ['id'=>267,'district'=> 'Samastipur','state_id'=> 5],
            ['id'=>268,'district'=> 'Saran','state_id'=> 5],
            ['id'=>269,'district'=> 'Sheikhpura','state_id'=> 5],
            ['id'=>270,'district'=> 'Sheohar','state_id'=> 5],
            ['id'=>271,'district'=> 'Sitamarhi','state_id'=> 5],
            ['id'=>272,'district'=> 'Siwan','state_id'=> 5],
            ['id'=>273,'district'=> 'Supaul','state_id'=> 5],
            ['id'=>274,'district'=> 'Vaishali','state_id'=> 5],
            ['id'=>275,'district'=> 'West Champaran','state_id'=> 5],
            ['id'=>276,'district'=> 'East Sikkim', 'state_id'=>30],
            ['id'=>277,'district'=> 'North Sikkim', 'state_id'=>30],
            ['id'=>278,'district'=> 'South Sikkim', 'state_id'=>30],
            ['id'=>279,'district'=> 'West Sikkim', 'state_id'=>30],
            ['id'=>280,'district'=> 'Anjaw','state_id'=> 3],
            ['id'=>281,'district'=> 'Changlang','state_id'=> 3],
            ['id'=>282,'district'=> 'Dibang Valley','state_id'=> 3],
            ['id'=>283,'district'=> 'East Kameng','state_id'=> 3],
            ['id'=>284,'district'=> 'East Siang','state_id'=> 3],
            ['id'=>285,'district'=> 'Kurung Kumey','state_id'=> 3],
            ['id'=>286,'district'=> 'Lohit','state_id'=> 3],
            ['id'=>287,'district'=> 'Lower Dibang Valley','state_id'=> 3],
            ['id'=>288,'district'=> 'Lower Subansiri','state_id'=> 3],
            ['id'=>289,'district'=> 'Papum Pare','state_id'=> 3],
            ['id'=>290,'district'=> 'Tawang','state_id'=> 3],
            ['id'=>291,'district'=> 'Tirap','state_id'=> 3],
            ['id'=>292,'district'=> 'Upper Siang','state_id'=> 3],
            ['id'=>293,'district'=> 'Upper Subansiri','state_id'=> 3],
            ['id'=>294,'district'=> 'West Kameng','state_id'=> 3],
            ['id'=>295,'district'=> 'West Siang','state_id'=> 3],
            ['id'=>296,'district'=> 'Dimapur', 'state_id'=>25],
            ['id'=>297,'district'=> 'Kiphire', 'state_id'=>25],
            ['id'=>298,'district'=> 'Kohima', 'state_id'=>25],
            ['id'=>299,'district'=> 'Longleng', 'state_id'=>25],
            ['id'=>300,'district'=> 'Mokokchung', 'state_id'=>25],
            ['id'=>301,'district'=> 'Mon', 'state_id'=>25],
            ['id'=>302,'district'=> 'Peren', 'state_id'=>25],
            ['id'=>303,'district'=> 'Phek', 'state_id'=>25],
            ['id'=>304,'district'=> 'Tuensang', 'state_id'=>25],
            ['id'=>305,'district'=> 'Wokha', 'state_id'=>25],
            ['id'=>306,'district'=> 'Zunheboto', 'state_id'=>25],
            ['id'=>307,'district'=> 'Bishnupur', 'state_id'=>22],
            ['id'=>308,'district'=> 'Chandel', 'state_id'=>22],
            ['id'=>309,'district'=> 'Churachandpur', 'state_id'=>22],
            ['id'=>310,'district'=> 'Imphal East', 'state_id'=>22],
            ['id'=>311,'district'=> 'Imphal West', 'state_id'=>22],
            ['id'=>312,'district'=> 'Senapati', 'state_id'=>22],
            ['id'=>313,'district'=> 'Tamenglong', 'state_id'=>22],
            ['id'=>314,'district'=> 'Thoubal', 'state_id'=>22],
            ['id'=>315,'district'=> 'Ukhrul', 'state_id'=>22],
            ['id'=>316,'district'=> 'Aizawl', 'state_id'=>24],
            ['id'=>317,'district'=> 'Champhai', 'state_id'=>24],
            ['id'=>318,'district'=> 'Kolasib', 'state_id'=>24],
            ['id'=>319,'district'=> 'Lawngtlai', 'state_id'=>24],
            ['id'=>320,'district'=> 'Lunglei', 'state_id'=>24],
            ['id'=>321,'district'=> 'Mamit', 'state_id'=>24],
            ['id'=>322,'district'=> 'Saiha', 'state_id'=>24],
            ['id'=>323,'district'=> 'Serchhip', 'state_id'=>24],
            ['id'=>324,'district'=> 'Dhalai', 'state_id'=>32],
            ['id'=>325,'district'=> 'North Tripura', 'state_id'=>32],
            ['id'=>326,'district'=> 'South Tripura', 'state_id'=>32],
            ['id'=>327,'district'=> 'West Tripura', 'state_id'=>32],
            ['id'=>328,'district'=> 'East Garo Hills', 'state_id'=>23],
            ['id'=>329,'district'=> 'East Khasi Hills', 'state_id'=>23],
            ['id'=>330,'district'=> 'Jaintia Hills', 'state_id'=>23],
            ['id'=>331,'district'=> 'Ri Bhoi', 'state_id'=>23],
            ['id'=>332,'district'=> 'South Garo Hills', 'state_id'=>23],
            ['id'=>333,'district'=> 'West Garo Hills', 'state_id'=>23],
            ['id'=>334,'district'=> 'West Khasi Hills', 'state_id'=>23],
            ['id'=>335,'district'=> 'Baksa','state_id'=> 4],
            ['id'=>336,'district'=> 'Barpeta','state_id'=> 4],
            ['id'=>337,'district'=> 'Bongaigaon','state_id'=> 4],
            ['id'=>338,'district'=> 'Cachar','state_id'=> 4],
            ['id'=>339,'district'=> 'Chirang','state_id'=> 4],
            ['id'=>340,'district'=> 'Darrang','state_id'=> 4],
            ['id'=>341,'district'=> 'Dhemaji','state_id'=> 4],
            ['id'=>342,'district'=> 'Dhubri','state_id'=> 4],
            ['id'=>343,'district'=> 'Dibrugarh','state_id'=> 4],
            ['id'=>344,'district'=> 'Dima Hasao (North Cachar Hills)','state_id'=> 4],
            ['id'=>345,'district'=> 'Goalpara','state_id'=> 4],
            ['id'=>346,'district'=> 'Golaghat','state_id'=> 4],
            ['id'=>347,'district'=> 'Hailakandi','state_id'=> 4],
            ['id'=>348,'district'=> 'Jorhat','state_id'=> 4],
            ['id'=>349,'district'=> 'Kamrup','state_id'=> 4],
            ['id'=>350,'district'=> 'Kamrup Metropolitan','state_id'=> 4],
            ['id'=>351,'district'=> 'Karbi Anglong','state_id'=> 4],
            ['id'=>352,'district'=> 'Karimganj','state_id'=> 4],
            ['id'=>353,'district'=> 'Kokrajhar','state_id'=> 4],
            ['id'=>354,'district'=> 'Lakhimpur','state_id'=> 4],
            ['id'=>355,'district'=> 'Morigaon','state_id'=> 4],
            ['id'=>356,'district'=> 'Nagaon','state_id'=> 4],
            ['id'=>357,'district'=> 'Nalbari','state_id'=> 4],
            ['id'=>358,'district'=> 'Sivasagar','state_id'=> 4],
            ['id'=>359,'district'=> 'Sonitpur','state_id'=> 4],
            ['id'=>360,'district'=> 'Tinsukia','state_id'=> 4],
            ['id'=>361,'district'=> 'Udalguri','state_id'=> 4],
            ['id'=>362,'district'=> 'Bankura', 'state_id'=>35],
            ['id'=>363,'district'=> 'Bardhaman', 'state_id'=>35],
            ['id'=>364,'district'=> 'Birbhum', 'state_id'=>35],
            ['id'=>365,'district'=> 'Cooch Behar', 'state_id'=>35],
            ['id'=>366,'district'=> 'Dakshin Dinajpur (South Dinajpur)','state_id'=> 35],
            ['id'=>367,'district'=> 'Darjiling', 'state_id'=>35],
            ['id'=>368,'district'=> 'Hooghly', 'state_id'=>35],
            ['id'=>369,'district'=> 'Howrah', 'state_id'=>35],
            ['id'=>370,'district'=> 'Jalpaiguri', 'state_id'=>35],
            ['id'=>371,'district'=> 'Kolkata', 'state_id'=>35],
            ['id'=>372,'district'=> 'Maldah', 'state_id'=>35],
            ['id'=>373,'district'=> 'Murshidabad', 'state_id'=>35],
            ['id'=>374,'district'=> 'Nadia', 'state_id'=>35],
            ['id'=>375,'district'=> 'North 24 Parganas', 'state_id'=>35],
            ['id'=>376,'district'=> 'Paschim Medinipur (West Midnapore)', 'state_id'=>35],
            ['id'=>377,'district'=> 'Purba Medinipur (East Midnapore)', 'state_id'=>35],
            ['id'=>378,'district'=> 'Puruliya', 'state_id'=>35],
            ['id'=>379,'district'=> 'South 24 Parganas', 'state_id'=>35],
            ['id'=>380,'district'=> 'Uttar Dinajpur (North Dinajpur)', 'state_id'=>35],
            ['id'=>381,'district'=> 'Bokaro', 'state_id'=>16],
            ['id'=>382,'district'=> 'Chatra', 'state_id'=>16],
            ['id'=>383,'district'=> 'Deoghar', 'state_id'=>16],
            ['id'=>384,'district'=> 'Dhanbad', 'state_id'=>16],
            ['id'=>385,'district'=> 'Dumka', 'state_id'=>16],
            ['id'=>386,'district'=> 'East Singhbhum', 'state_id'=>16],
            ['id'=>387,'district'=> 'Garhwa', 'state_id'=>16],
            ['id'=>388,'district'=> 'Giridih', 'state_id'=>16],
            ['id'=>389,'district'=> 'Godda', 'state_id'=>16],
            ['id'=>390,'district'=> 'Gumla', 'state_id'=>16],
            ['id'=>391,'district'=> 'Hazaribagh', 'state_id'=>16],
            ['id'=>392,'district'=> 'Jamtara', 'state_id'=>16],
            ['id'=>393,'district'=> 'Khunti', 'state_id'=>16],
            ['id'=>394,'district'=> 'Koderma', 'state_id'=>16],
            ['id'=>395,'district'=> 'Latehar', 'state_id'=>16],
            ['id'=>396,'district'=> 'Lohardaga', 'state_id'=>16],
            ['id'=>397,'district'=> 'Pakur', 'state_id'=>16],
            ['id'=>398,'district'=> 'Palamu', 'state_id'=>16],
            ['id'=>399,'district'=> 'Ramgarh', 'state_id'=>16],
            ['id'=>400,'district'=> 'Ranchi', 'state_id'=>16],
            ['id'=>401,'district'=> 'Sahibganj', 'state_id'=>16],
            ['id'=>402,'district'=> 'Seraikela-Kharsawan', 'state_id'=>16],
            ['id'=>403,'district'=> 'Simdega', 'state_id'=>16],
            ['id'=>404,'district'=> 'West Singhbhum', 'state_id'=>16],
            ['id'=>405,'district'=> 'Angul', 'state_id'=>26],
            ['id'=>406,'district'=> 'Balangir', 'state_id'=>26],
            ['id'=>407,'district'=> 'Baleswar', 'state_id'=>26],
            ['id'=>408,'district'=> 'Bargarh', 'state_id'=>26],
            ['id'=>409,'district'=> 'Bhadrak', 'state_id'=>26],
            ['id'=>410,'district'=> 'Boudh', 'state_id'=>26],
            ['id'=>411,'district'=> 'Cuttack', 'state_id'=>26],
            ['id'=>412,'district'=> 'Debagarh', 'state_id'=>26],
            ['id'=>413,'district'=> 'Dhenkanal', 'state_id'=>26],
            ['id'=>414,'district'=> 'Gajapati', 'state_id'=>26],
            ['id'=>415,'district'=> 'Ganjam', 'state_id'=>26],
            ['id'=>416,'district'=> 'Jagatsinghapur', 'state_id'=>26],
            ['id'=>417,'district'=> 'Jajapur', 'state_id'=>26],
            ['id'=>418,'district'=> 'Jharsuguda', 'state_id'=>26],
            ['id'=>419,'district'=> 'Kalahandi', 'state_id'=>26],
            ['id'=>420,'district'=> 'Kandhamal', 'state_id'=>26],
            ['id'=>421,'district'=> 'Kendrapara', 'state_id'=>26],
            ['id'=>422,'district'=> 'Kendujhar', 'state_id'=>26],
            ['id'=>423,'district'=> 'Khordha', 'state_id'=>26],
            ['id'=>424,'district'=> 'Koraput', 'state_id'=>26],
            ['id'=>425,'district'=> 'Malkangiri', 'state_id'=>26],
            ['id'=>426,'district'=> 'Mayurbhanj', 'state_id'=>26],
            ['id'=>427,'district'=> 'Nabarangapur', 'state_id'=>26],
            ['id'=>428,'district'=> 'Nayagarh', 'state_id'=>26],
            ['id'=>429,'district'=> 'Nuapada', 'state_id'=>26],
            ['id'=>430,'district'=> 'Puri', 'state_id'=>26],
            ['id'=>431,'district'=> 'Rayagada', 'state_id'=>26],
            ['id'=>432,'district'=> 'Sambalpur', 'state_id'=>26],
            ['id'=>433,'district'=> 'Subarnapur (Sonapur)', 'state_id'=>26],
            ['id'=>434,'district'=> 'Sundergarh', 'state_id'=>26],
            ['id'=>435,'district'=> 'Bastar','state_id'=> 7],
            ['id'=>436,'district'=> 'Bijapur (Chhattisgarh)','state_id'=> 7],
            ['id'=>437,'district'=> 'Bilaspur (Chhattisgarh)','state_id'=> 7],
            ['id'=>438,'district'=> 'Dakshin Bastar Dantewada','state_id'=> 7],
            ['id'=>439,'district'=> 'Dhamtari','state_id'=> 7],
            ['id'=>440,'district'=> 'Durg','state_id'=> 7],
            ['id'=>441,'district'=> 'Janjgir-Champa','state_id'=> 7],
            ['id'=>442,'district'=> 'Jashpur','state_id'=> 7],
            ['id'=>443,'district'=> 'Kabirdham (Kawardha)','state_id'=> 7],
            ['id'=>444,'district'=> 'Korba','state_id'=> 7],
            ['id'=>445,'district'=> 'Koriya','state_id'=> 7],
            ['id'=>446,'district'=> 'Mahasamund','state_id'=> 7],
            ['id'=>447,'district'=> 'Narayanpur','state_id'=> 7],
            ['id'=>448,'district'=> 'Raigarh (Chhattisgarh)','state_id'=> 7],
            ['id'=>449,'district'=> 'Raipur','state_id'=> 7],
            ['id'=>450,'district'=> 'Rajnandgaon','state_id'=> 7],
            ['id'=>451,'district'=> 'Surguja','state_id'=> 7],
            ['id'=>452,'district'=> 'Uttar Bastar Kanker','state_id'=> 7],
            ['id'=>453,'district'=> 'Alirajpur', 'state_id'=>20],
            ['id'=>454,'district'=> 'Anuppur', 'state_id'=>20],
            ['id'=>455,'district'=> 'Ashok Nagar', 'state_id'=>20],
            ['id'=>456,'district'=> 'Balaghat', 'state_id'=>20],
            ['id'=>457,'district'=> 'Barwani', 'state_id'=>20],
            ['id'=>458,'district'=> 'Betul', 'state_id'=>20],
            ['id'=>459,'district'=> 'Bhind', 'state_id'=>20],
            ['id'=>460,'district'=> 'Bhopal', 'state_id'=>20],
            ['id'=>461,'district'=> 'Burhanpur', 'state_id'=>20],
            ['id'=>462,'district'=> 'Chhatarpur', 'state_id'=>20],
            ['id'=>463,'district'=> 'Chhindwara', 'state_id'=>20],
            ['id'=>464,'district'=> 'Damoh', 'state_id'=>20],
            ['id'=>465,'district'=> 'Datia', 'state_id'=>20],
            ['id'=>466,'district'=> 'Dewas', 'state_id'=>20],
            ['id'=>467,'district'=> 'Dhar', 'state_id'=>20],
            ['id'=>468,'district'=> 'Dindori', 'state_id'=>20],
            ['id'=>469,'district'=> 'Guna', 'state_id'=>20],
            ['id'=>470,'district'=> 'Gwalior', 'state_id'=>20],
            ['id'=>471,'district'=> 'Harda', 'state_id'=>20],
            ['id'=>472,'district'=> 'Hoshangabad', 'state_id'=>20],
            ['id'=>473,'district'=> 'Indore', 'state_id'=>20],
            ['id'=>474,'district'=> 'Jabalpur', 'state_id'=>20],
            ['id'=>475,'district'=> 'Jhabua', 'state_id'=>20],
            ['id'=>476,'district'=> 'Katni', 'state_id'=>20],
            ['id'=>477,'district'=> 'Khandwa (East Nimar)', 'state_id'=>20],
            ['id'=>478,'district'=> 'Khargone (West Nimar)', 'state_id'=>20],
            ['id'=>479,'district'=> 'Mandla', 'state_id'=>20],
            ['id'=>480,'district'=> 'Mandsaur', 'state_id'=>20],
            ['id'=>481,'district'=> 'Morena', 'state_id'=>20],
            ['id'=>482,'district'=> 'Narsinghpur', 'state_id'=>20],
            ['id'=>483,'district'=> 'Neemuch', 'state_id'=>20],
            ['id'=>484,'district'=> 'Panna', 'state_id'=>20],
            ['id'=>485,'district'=> 'Raisen', 'state_id'=>20],
            ['id'=>486,'district'=> 'Rajgarh', 'state_id'=>20],
            ['id'=>487,'district'=> 'Ratlam', 'state_id'=>20],
            ['id'=>488,'district'=> 'Rewa', 'state_id'=>20],
            ['id'=>489,'district'=> 'Sagar', 'state_id'=>20],
            ['id'=>490,'district'=> 'Satna', 'state_id'=>20],
            ['id'=>491,'district'=> 'Sehore', 'state_id'=>20],
            ['id'=>492,'district'=> 'Seoni', 'state_id'=>20],
            ['id'=>493,'district'=> 'Shahdol', 'state_id'=>20],
            ['id'=>494,'district'=> 'Shajapur', 'state_id'=>20],
            ['id'=>495,'district'=> 'Sheopur', 'state_id'=>20],
            ['id'=>496,'district'=> 'Shivpuri', 'state_id'=>20],
            ['id'=>497,'district'=> 'Sidhi', 'state_id'=>20],
            ['id'=>498,'district'=> 'Singrauli', 'state_id'=>20],
            ['id'=>499,'district'=> 'Tikamgarh', 'state_id'=>20],
            ['id'=>500,'district'=> 'Ujjain', 'state_id'=>20],
            ['id'=>501,'district'=> 'Umaria', 'state_id'=>20],
            ['id'=>502,'district'=> 'Vidisha', 'state_id'=>20],
            ['id'=>503,'district'=> 'Ahmedabad', 'state_id'=>12],
            ['id'=>504,'district'=> 'Amreli', 'state_id'=>12],
            ['id'=>505,'district'=> 'Anand', 'state_id'=>12],
            ['id'=>506,'district'=> 'Banaskantha', 'state_id'=>12],
            ['id'=>507,'district'=> 'Bharuch', 'state_id'=>12],
            ['id'=>508,'district'=> 'Bhavnagar', 'state_id'=>12],
            ['id'=>509,'district'=> 'Dahod', 'state_id'=>12],
            ['id'=>510,'district'=> 'Gandhi Nagar', 'state_id'=>12],
            ['id'=>511,'district'=> 'Jamnagar', 'state_id'=>12],
            ['id'=>512,'district'=> 'Junagadh', 'state_id'=>12],
            ['id'=>513,'district'=> 'Kachchh', 'state_id'=>12],
            ['id'=>514,'district'=> 'Kheda', 'state_id'=>12],
            ['id'=>515,'district'=> 'Mahesana', 'state_id'=>12],
            ['id'=>516,'district'=> 'Narmada', 'state_id'=>12],
            ['id'=>517,'district'=> 'Navsari', 'state_id'=>12],
            ['id'=>518,'district'=> 'Panch Mahals', 'state_id'=>12],
            ['id'=>519,'district'=> 'Patan', 'state_id'=>12],
            ['id'=>520,'district'=> 'Porbandar', 'state_id'=>12],
            ['id'=>521,'district'=> 'Rajkot', 'state_id'=>12],
            ['id'=>522,'district'=> 'Sabarkantha', 'state_id'=>12],
            ['id'=>523,'district'=> 'Surat', 'state_id'=>12],
            ['id'=>524,'district'=> 'Surendra Nagar', 'state_id'=>12],
            ['id'=>525,'district'=> 'Tapi', 'state_id'=>12],
            ['id'=>526,'district'=> 'The Dangs', 'state_id'=>12],
            ['id'=>527,'district'=> 'Vadodara', 'state_id'=>12],
            ['id'=>528,'district'=> 'Valsad', 'state_id'=>12],
            ['id'=>529,'district'=> 'Daman','state_id'=> 9],
            ['id'=>530,'district'=> 'Diu','state_id'=> 9],
            ['id'=>531,'district'=> 'Dadra & Nagar Haveli','state_id'=> 8],
            ['id'=>532,'district'=> 'Ahmed Nagar', 'state_id'=>21],
            ['id'=>533,'district'=> 'Akola', 'state_id'=>21],
            ['id'=>534,'district'=> 'Amravati', 'state_id'=>21],
            ['id'=>535,'district'=> 'Aurangabad', 'state_id'=>21],
            ['id'=>536,'district'=> 'Beed', 'state_id'=>21],
            ['id'=>537,'district'=> 'Bhandara', 'state_id'=>21],
            ['id'=>538,'district'=> 'Buldhana', 'state_id'=>21],
            ['id'=>539,'district'=> 'Chandrapur', 'state_id'=>21],
            ['id'=>540,'district'=> 'Dhule', 'state_id'=>21],
            ['id'=>541,'district'=> 'Gadchiroli', 'state_id'=>21],
            ['id'=>542,'district'=> 'Gondia', 'state_id'=>21],
            ['id'=>543,'district'=> 'Hingoli', 'state_id'=>21],
            ['id'=>544,'district'=> 'Jalgaon', 'state_id'=>21],
            ['id'=>545,'district'=> 'Jalna', 'state_id'=>21],
            ['id'=>546,'district'=> 'Kolhapur', 'state_id'=>21],
            ['id'=>547,'district'=> 'Latur', 'state_id'=>21],
            ['id'=>548,'district'=> 'Mumbai', 'state_id'=>21],
            ['id'=>549,'district'=> 'Mumbai Suburban', 'state_id'=>21],
            ['id'=>550,'district'=> 'Nagpur', 'state_id'=>21],
            ['id'=>551,'district'=> 'Nanded', 'state_id'=>21],
            ['id'=>552,'district'=> 'Nandurbar', 'state_id'=>21],
            ['id'=>553,'district'=> 'Nashik', 'state_id'=>21],
            ['id'=>554,'district'=> 'Osmanabad', 'state_id'=>21],
            ['id'=>555,'district'=> 'Parbhani', 'state_id'=>21],
            ['id'=>556,'district'=> 'Pune', 'state_id'=>21],
            ['id'=>557,'district'=> 'Raigarh(Maharashtra)', 'state_id'=>21],
            ['id'=>558,'district'=> 'Ratnagiri', 'state_id'=>21],
            ['id'=>559,'district'=> 'Sangli', 'state_id'=>21],
            ['id'=>560,'district'=> 'Satara', 'state_id'=>21],
            ['id'=>561,'district'=> 'Sindhudurg', 'state_id'=>21],
            ['id'=>562,'district'=> 'Solapur', 'state_id'=>21],
            ['id'=>563,'district'=> 'Thane', 'state_id'=>21],
            ['id'=>564,'district'=> 'Wardha', 'state_id'=>21],
            ['id'=>565,'district'=> 'Washim', 'state_id'=>21],
            ['id'=>566,'district'=> 'Yavatmal', 'state_id'=>21],
            ['id'=>567,'district'=> 'Adilabad','state_id'=> 2],
            ['id'=>568,'district'=> 'Anantapur','state_id'=> 2],
            ['id'=>569,'district'=> 'Chittoor','state_id'=> 2],
            ['id'=>570,'district'=> 'East Godavari','state_id'=> 2],
            ['id'=>571,'district'=> 'Guntur','state_id'=> 2],
            ['id'=>572,'district'=> 'Hyderabad','state_id'=> 2],
            ['id'=>573,'district'=> 'Kadapa (Cuddapah)','state_id'=> 2],
            ['id'=>574,'district'=> 'Karim Nagar','state_id'=> 2],
            ['id'=>575,'district'=> 'Khammam','state_id'=> 2],
            ['id'=>576,'district'=> 'Krishna','state_id'=> 2],
            ['id'=>577,'district'=> 'Kurnool','state_id'=> 2],
            ['id'=>578,'district'=> 'Mahbubnagar','state_id'=> 2],
            ['id'=>579,'district'=> 'Medak','state_id'=> 2],
            ['id'=>580,'district'=> 'Nalgonda','state_id'=> 2],
            ['id'=>581,'district'=> 'Nellore','state_id'=> 2],
            ['id'=>582,'district'=> 'Nizamabad','state_id'=> 2],
            ['id'=>583,'district'=> 'Prakasam','state_id'=> 2],
            ['id'=>584,'district'=> 'Rangareddy','state_id'=> 2],
            ['id'=>585,'district'=> 'Srikakulam','state_id'=> 2],
            ['id'=>586,'district'=> 'Visakhapatnam','state_id'=> 2],
            ['id'=>587,'district'=> 'Vizianagaram','state_id'=> 2],
            ['id'=>588,'district'=> 'Warangal','state_id'=> 2],
            ['id'=>589,'district'=> 'West Godavari','state_id'=> 2],
            ['id'=>590,'district'=> 'Bagalkot', 'state_id'=>17],
            ['id'=>591,'district'=> 'Bangalore', 'state_id'=>17],
            ['id'=>592,'district'=> 'Bangalore Rural', 'state_id'=>17],
            ['id'=>593,'district'=> 'Belgaum', 'state_id'=>17],
            ['id'=>594,'district'=> 'Bellary', 'state_id'=>17],
            ['id'=>595,'district'=> 'Bidar', 'state_id'=>17],
            ['id'=>596,'district'=> 'Bijapur (Karnataka)', 'state_id'=>17],
            ['id'=>597,'district'=> 'Chamrajnagar', 'state_id'=>17],
            ['id'=>598,'district'=> 'Chickmagalur', 'state_id'=>17],
            ['id'=>599,'district'=> 'Chikkaballapur', 'state_id'=>17],
            ['id'=>600,'district'=> 'Chitradurga', 'state_id'=>17],
            ['id'=>601,'district'=> 'Dakshina Kannada', 'state_id'=>17],
            ['id'=>602,'district'=> 'Davanagere', 'state_id'=>17],
            ['id'=>603,'district'=> 'Dharwad', 'state_id'=>17],
            ['id'=>604,'district'=> 'Gadag', 'state_id'=>17],
            ['id'=>605,'district'=> 'Gulbarga', 'state_id'=>17],
            ['id'=>606,'district'=> 'Hassan', 'state_id'=>17],
            ['id'=>607,'district'=> 'Haveri', 'state_id'=>17],
            ['id'=>608,'district'=> 'Kodagu', 'state_id'=>17],
            ['id'=>609,'district'=> 'Kolar', 'state_id'=>17],
            ['id'=>610,'district'=> 'Koppal', 'state_id'=>17],
            ['id'=>611,'district'=> 'Mandya', 'state_id'=>17],
            ['id'=>612,'district'=> 'Mysore', 'state_id'=>17],
            ['id'=>613,'district'=> 'Raichur', 'state_id'=>17],
            ['id'=>614,'district'=> 'Ramanagara', 'state_id'=>17],
            ['id'=>615,'district'=> 'Shimoga', 'state_id'=>17],
            ['id'=>616,'district'=> 'Tumkur', 'state_id'=>17],
            ['id'=>617,'district'=> 'Udupi', 'state_id'=>17],
            ['id'=>618,'district'=> 'Uttara Kannada', 'state_id'=>17],
            ['id'=>619,'district'=> 'Yadgir', 'state_id'=>17],
            ['id'=>620,'district'=> 'North Goa', 'state_id'=>11],
            ['id'=>621,'district'=> 'South Goa', 'state_id'=>11],
            ['id'=>622,'district'=> 'Lakshadweep', 'state_id'=>19],
            ['id'=>623,'district'=> 'Alappuzha', 'state_id'=>18],
            ['id'=>624,'district'=> 'Ernakulam', 'state_id'=>18],
            ['id'=>625,'district'=> 'Idukki', 'state_id'=>18],
            ['id'=>626,'district'=> 'Kannur', 'state_id'=>18],
            ['id'=>627,'district'=> 'Kasaragod', 'state_id'=>18],
            ['id'=>628,'district'=> 'Kollam', 'state_id'=>18],
            ['id'=>629,'district'=> 'Kottayam', 'state_id'=>18],
            ['id'=>630,'district'=> 'Kozhikode', 'state_id'=>18],
            ['id'=>631,'district'=> 'Malappuram', 'state_id'=>18],
            ['id'=>632,'district'=> 'Palakkad', 'state_id'=>18],
            ['id'=>633,'district'=> 'Pathanamthitta', 'state_id'=>18],
            ['id'=>634,'district'=> 'Thiruvananthapuram', 'state_id'=>18],
            ['id'=>635,'district'=> 'Thrissur', 'state_id'=>18],
            ['id'=>636,'district'=> 'Wayanad', 'state_id'=>18],
            ['id'=>637,'district'=> 'Ariyalur', 'state_id'=>31],
            ['id'=>638,'district'=> 'Chennai', 'state_id'=>31],
            ['id'=>639,'district'=> 'Coimbatore', 'state_id'=>31],
            ['id'=>640,'district'=> 'Cuddalore', 'state_id'=>31],
            ['id'=>641,'district'=> 'Dharmapuri', 'state_id'=>31],
            ['id'=>642,'district'=> 'Dindigul', 'state_id'=>31],
            ['id'=>643,'district'=> 'Erode', 'state_id'=>31],
            ['id'=>644,'district'=> 'Kanchipuram', 'state_id'=>31],
            ['id'=>645,'district'=> 'Kanyakumari', 'state_id'=>31],
            ['id'=>646,'district'=> 'Karur', 'state_id'=>31],
            ['id'=>647,'district'=> 'Krishnagiri', 'state_id'=>31],
            ['id'=>648,'district'=> 'Madurai', 'state_id'=>31],
            ['id'=>649,'district'=> 'Nagapattinam', 'state_id'=>31],
            ['id'=>650,'district'=> 'Namakkal', 'state_id'=>31],
            ['id'=>651,'district'=> 'Nilgiris', 'state_id'=>31],
            ['id'=>652,'district'=> 'Perambalur', 'state_id'=>31],
            ['id'=>653,'district'=> 'Pudukkottai', 'state_id'=>31],
            ['id'=>654,'district'=> 'Ramanathapuram', 'state_id'=>31],
            ['id'=>655,'district'=> 'Salem', 'state_id'=>31],
            ['id'=>656,'district'=> 'Sivaganga', 'state_id'=>31],
            ['id'=>657,'district'=> 'Thanjavur', 'state_id'=>31],
            ['id'=>658,'district'=> 'Theni', 'state_id'=>31],
            ['id'=>659,'district'=> 'Thoothukudi(Tuticorin)', 'state_id'=>31],
            ['id'=>660,'district'=> 'Tiruchirappalli', 'state_id'=>31],
            ['id'=>661,'district'=> 'Tirunelveli', 'state_id'=>31],
            ['id'=>662,'district'=> 'Tiruppur', 'state_id'=>31],
            ['id'=>663,'district'=> 'Tiruvallur', 'state_id'=>31],
            ['id'=>664,'district'=> 'Tiruvannamalai', 'state_id'=>31],
            ['id'=>665,'district'=> 'Tiruvarur', 'state_id'=>31],
            ['id'=>666,'district'=> 'Vellore', 'state_id'=>31],
            ['id'=>667,'district'=> 'Viluppuram', 'state_id'=>31],
            ['id'=>668,'district'=> 'Virudhunagar', 'state_id'=>31],
            ['id'=>669,'district'=> 'Karaikal', 'state_id'=>27],
            ['id'=>670,'district'=> 'Mahe', 'state_id'=>27],
            ['id'=>671,'district'=> 'Puducherry (Pondicherry)', 'state_id'=>27],
            ['id'=>672,'district'=> 'Yanam', 'state_id'=>27],
            ['id'=>673,'district'=> 'Nicobar','state_id'=> 1],
            ['id'=>674,'district'=> 'North And Middle Andaman','state_id'=> 1],
            ['id'=>675,'district'=> 'South Andaman','state_id'=> 1],        
        ];
       
        DB::table('districts')->insert($districts);
    }
}
